### ISSUE TITLE
如果创造具体对象的条件有多个呢？

### ISSUE THREAD

**Issue by herokang** [qicosmos/cosmos#12]
从http://blog.csdn.net/afei198409/article/details/50448296 看到问题

创造函数保存在map中，
即 `static std::map<std::string, std::function<Message * ()>> map_;`
如果创造具体对象的条件有多个呢？该怎么去设计这个映射？嵌套map吗？

譬如，用简单工厂大致描述需求如下：
```
switch(factor_1) {
 case 1:
   switch(factor_2) {
   case 1:
       returan new product_1_1();
       break;
   case 2:
       returan new product_1_2();
       break;
    }
 break;
 case 2:
   switch(factor_2) {
   case 1:
       returan new product_2_1();
       break;
   case 2:
       returan new product_2_2();
       break;
    }
 break;
}
```

**Comment by qicosmos** [comment]
switch中再嵌套switch这个思路不对，应该让key唯一，不应该嵌套。

**Comment by herokang** [comment]
如果不可避免的有这种多层判断的条件呢？譬如，某类型的product下有更细分的子类型。
这样的话，怎么去实现factory比较合适

**Comment by qicosmos** [comment]
那就创建多个工厂吧，加一个子工厂就好了。

**Comment by shaoyuan1943** [comment]
创建多个工厂的话，当子类型越多的时候子工厂也就会越多，可维护性和复杂度也许日益下降，是否可以考虑尽可能的剥离共性，以参数区分子类型？

**Comment by qicosmos** [comment]
工厂嵌套工厂本身就不是好的做法，好的做法应该是保持创建的维度一维，尽量用key来区分。如果确实需要嵌套的话，还不如把key分成两部分，比如高位代表大的分类，地位代表小的分类。这已经是比较复杂了，我始终觉得switch嵌套switch不是一个好的做法。

**Comment by shaoyuan1943** [comment]
工厂的确要尽可能保持一维，如果将key拆分为两部分的话，那最好的还是保持key唯一。

**Comment by qicosmos** [comment]
对的。
