### ISSUE TITLE
LinqCpp编译报错，尝试了各种办法，没能解决，求助。

### ISSUE THREAD

**Issue by yangtsecxf** [qicosmos/cosmos#45]
**在LinqCpp.hpp的下面代码中：**

template<typename F>
auto last(const F& f) -> decltype(reverse().first(f))
{
	return reverse().first(f);
}

**遇到了如下编译错误：**
LinqCpp.hpp(72,44): error C2672: 'reverse': no matching overloaded function found

**环境：**
visual studio 2019
c++17
boost_1_76_0-msvc-14.2-32

**Comment by qicosmos** [comment]
这个有好久没维护了，现在ranges库已经很全面很强大了，建议用ranges库呀。

**Comment by yangtsecxf** [comment]
谢谢提醒 我觉得你的LinqCpp.hpp 代码非常优雅 功能也很强大 或许工作中用得上 我按照range库来改写试试。
